<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Authors>Cyberkyd</Authors>
    <Company>Cyberkyd</Company>
    <Product>Voice Changer Pro by Cyberkyd</Product>
    <Copyright>Copyright © 2026 Cyberkyd</Copyright>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
</Project>
